name: ci
on:
  push:
    branches-ignore:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lint:
          - eslint
          - stylelint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-
      - run: yarn install --frozen-lockfile

      - name: Run ${{ matrix.lint }}
        run: yarn ${{ matrix.lint }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache.outputs.dir }}
            ./.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-
      - run: yarn install --frozen-lockfile

      - name: Run build
        run: |
          yarn build
          yarn export
        env:
          NEXT_PUBLIC_BASE_URL: ${{ secrets.BASE_URL }}
          NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: out

  deploy:
    runs-on: ubuntu-latest
    needs:
      - lint
      - build
    if: github.ref == 'refs/tags/dev'
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          publish_dir: ./
          publish_branch: master
          cname: ${{ secrets.BASE_URL }}
