name: deploy
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-
            ${{ runner.os }}-
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile

      - name: run build
        run: |
          yarn build
          yarn export
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

      - name: upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: out
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: download artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          publish_dir: ./artifact
          publish_branch: master
          cname: ${{ secrets.BASE_URL }}
