name: Workflow
on: [push, pull_request]

jobs:
  code-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-
            ${{ runner.os }}-
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Code lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ github.ref }}-
            ${{ runner.os }}-
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
        run: |
          yarn build
          yarn export

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: out

  deploy:
    runs-on: ubuntu-latest
    needs:
      - code-lint
      - build
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          publish_dir: ./artifact
          publish_branch: master
          cname: ${{ secrets.BASE_URL }}
